-- ═══════════════════════════════════════════════════════════════════
-- Migration 05 · Product Management & Approval Workflow
-- Tables:
--   PRODUCT_CHANGE_REQUESTS  — add/remove requests with approval flow
--   PRODUCT_FORECASTS        — quarterly profit forecasts (LLM-generated)
-- Idempotent: safe to re-run (ORA-00955 / ORA-01408 silently swallowed)
-- ═══════════════════════════════════════════════════════════════════

-- ── 1. PRODUCT_CHANGE_REQUESTS ──────────────────────────────────────
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE PRODUCT_CHANGE_REQUESTS (
      REQUEST_ID       VARCHAR2(50)   PRIMARY KEY,
      CUSTOMER_ID      VARCHAR2(50)   NOT NULL REFERENCES CUSTOMERS(CUSTOMER_ID),
      HOLDING_ID       NUMBER,
      PRODUCT_ID       VARCHAR2(50)   REFERENCES PRODUCT_CATALOG(PRODUCT_ID),
      PRODUCT_NAME     VARCHAR2(200),
      PRODUCT_CATEGORY VARCHAR2(100),
      ACTION           VARCHAR2(10)   NOT NULL,
      STATUS           VARCHAR2(30)   DEFAULT 'PENDING_EXECUTION' NOT NULL,
      AMOUNT           NUMBER(20,2),
      SOURCE           VARCHAR2(20)   DEFAULT 'MANUAL',
      HISTORY_ID       VARCHAR2(50),
      REQUESTED_BY     VARCHAR2(50)   NOT NULL REFERENCES RM_USERS(USER_ID),
      APPROVED_BY      VARCHAR2(50)   REFERENCES RM_USERS(USER_ID),
      REJECTION_REASON VARCHAR2(1000),
      IMPACT_WARNING   CLOB,
      NOTES            VARCHAR2(2000),
      REQUESTED_AT     TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
      UPDATED_AT       TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT CHK_PCR_ACTION CHECK (ACTION IN ('ADD','REMOVE')),
      CONSTRAINT CHK_PCR_STATUS CHECK (STATUS IN (
        'PENDING_EXECUTION','PENDING_APPROVAL','APPROVED','REJECTED','EXECUTED','CANCELLED'
      )),
      CONSTRAINT CHK_PCR_SOURCE CHECK (SOURCE IN ('AI_RECOMMENDED','MANUAL'))
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ── 2. PRODUCT_FORECASTS ────────────────────────────────────────────
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE PRODUCT_FORECASTS (
      FORECAST_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      REQUEST_ID     VARCHAR2(50)  NOT NULL,
      CUSTOMER_ID    VARCHAR2(50),
      PRODUCT_ID     VARCHAR2(50),
      Q1_RETURN      NUMBER(20,2)  DEFAULT 0,
      Q2_RETURN      NUMBER(20,2)  DEFAULT 0,
      Q3_RETURN      NUMBER(20,2)  DEFAULT 0,
      Q4_RETURN      NUMBER(20,2)  DEFAULT 0,
      Q1_LABEL       VARCHAR2(50),
      Q2_LABEL       VARCHAR2(50),
      Q3_LABEL       VARCHAR2(50),
      Q4_LABEL       VARCHAR2(50),
      ANNUAL_RETURN  NUMBER(20,2)  DEFAULT 0,
      NARRATIVE      CLOB,
      MODEL_USED     VARCHAR2(200),
      CREATED_AT     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT FK_PF_REQUEST FOREIGN KEY (REQUEST_ID)
        REFERENCES PRODUCT_CHANGE_REQUESTS(REQUEST_ID) ON DELETE CASCADE
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ── 3. Indexes ──────────────────────────────────────────────────────
BEGIN
  EXECUTE IMMEDIATE
    'CREATE INDEX IDX_PCR_CUST_STATUS ON PRODUCT_CHANGE_REQUESTS (CUSTOMER_ID, STATUS)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE
    'CREATE INDEX IDX_PCR_REQBY_AT ON PRODUCT_CHANGE_REQUESTS (REQUESTED_BY, REQUESTED_AT DESC)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE
    'CREATE INDEX IDX_PF_REQUEST ON PRODUCT_FORECASTS (REQUEST_ID)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
