-- Migration 09: COPILOT_SUGGESTED_PROMPTS
-- Stores dynamic suggested prompts for the AI Copilot sidebar.
-- Run once via: node scripts/runMigration09.js

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE COPILOT_SUGGESTED_PROMPTS (
      PROMPT_ID    NUMBER        GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      PROMPT_TEXT  VARCHAR2(500) NOT NULL,
      CATEGORY     VARCHAR2(50)  DEFAULT 'general'  NOT NULL,
      ICON         VARCHAR2(20)  DEFAULT '💡'       NOT NULL,
      SORT_ORDER   NUMBER        DEFAULT 0           NOT NULL,
      IS_ACTIVE    NUMBER(1)     DEFAULT 1           NOT NULL,
      CREATED_AT   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- Index for active + sort
BEGIN
  EXECUTE IMMEDIATE
    'CREATE INDEX IDX_CSP_ACTIVE_SORT ON COPILOT_SUGGESTED_PROMPTS(IS_ACTIVE, SORT_ORDER)';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
