-- =============================================================================
-- 15_CUSTOMER_FINANCIAL_PROFILE.sql
-- Adds CIF number, income sources, and credit card data for Customer 360
-- target UI (docs screenshot: Budi Santoso profile card layout).
--
-- New objects:
--   1. CUSTOMERS.CIF_NUMBER      (column)
--   2. CUSTOMER_INCOME_SOURCES   (table)
--   3. CREDIT_CARDS              (table)
-- =============================================================================

SET SERVEROUTPUT ON SIZE UNLIMITED;

-- =============================================================================
-- STEP 1: Add CIF_NUMBER to CUSTOMERS
-- =============================================================================

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE CUSTOMERS ADD (CIF_NUMBER VARCHAR2(20))';
  DBMS_OUTPUT.PUT_LINE('[1] CIF_NUMBER column added.');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -1430 THEN
      DBMS_OUTPUT.PUT_LINE('[1] CIF_NUMBER already exists — skipping.');
    ELSE RAISE; END IF;
END;
/

-- Populate CIF numbers (DAN-XXXXXXX format)
UPDATE CUSTOMERS SET CIF_NUMBER = 'DAN-0041872' WHERE CUSTOMER_ID = 'CUST001';
UPDATE CUSTOMERS SET CIF_NUMBER = 'DAN-0052341' WHERE CUSTOMER_ID = 'CUST002';
UPDATE CUSTOMERS SET CIF_NUMBER = 'DAN-0063819' WHERE CUSTOMER_ID = 'CUST003';
UPDATE CUSTOMERS SET CIF_NUMBER = 'DAN-0074256' WHERE CUSTOMER_ID = 'CUST004';
UPDATE CUSTOMERS SET CIF_NUMBER = 'DAN-0085103' WHERE CUSTOMER_ID = 'CUST005';
UPDATE CUSTOMERS SET CIF_NUMBER = 'DAN-0096478' WHERE CUSTOMER_ID = 'CUST006';
UPDATE CUSTOMERS SET CIF_NUMBER = 'DAN-0107932' WHERE CUSTOMER_ID = 'CUST007';
COMMIT;
BEGIN DBMS_OUTPUT.PUT_LINE('[1] CIF numbers populated.'); END;
/

-- =============================================================================
-- STEP 2: CUSTOMER_INCOME_SOURCES table
-- =============================================================================

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CUSTOMER_INCOME_SOURCES PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE CUSTOMER_INCOME_SOURCES (
  INCOME_ID     NUMBER         GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CUSTOMER_ID   VARCHAR2(20)   NOT NULL REFERENCES CUSTOMERS(CUSTOMER_ID),
  SOURCE_NAME   VARCHAR2(100)  NOT NULL,  -- e.g. "Pension (BPJS)", "Rental Income"
  SOURCE_TYPE   VARCHAR2(30)   NOT NULL,  -- pension / salary / rental / business / dividend / freelance
  AMOUNT        NUMBER(20,2)   NOT NULL,
  UNIT_COUNT    NUMBER(5)      DEFAULT NULL,  -- e.g. 2 for "2 units" of rental
  ICON          VARCHAR2(10)   DEFAULT NULL,  -- emoji icon
  SORT_ORDER    NUMBER(3)      DEFAULT 1,
  IS_ACTIVE     NUMBER(1)      DEFAULT 1,
  CREATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_INCOME_CUST ON CUSTOMER_INCOME_SOURCES(CUSTOMER_ID);

BEGIN DBMS_OUTPUT.PUT_LINE('[2] CUSTOMER_INCOME_SOURCES created.'); END;
/

-- CUST001 Budi Santoso — Conservative, Prioritas (income total 85M in DB)
INSERT INTO CUSTOMER_INCOME_SOURCES (CUSTOMER_ID,SOURCE_NAME,SOURCE_TYPE,AMOUNT,UNIT_COUNT,ICON,SORT_ORDER)
VALUES ('CUST001','Pension (BPJS)','pension',55000000,NULL,'🏛',1);
INSERT INTO CUSTOMER_INCOME_SOURCES (CUSTOMER_ID,SOURCE_NAME,SOURCE_TYPE,AMOUNT,UNIT_COUNT,ICON,SORT_ORDER)
VALUES ('CUST001','Rental Income','rental',30000000,2,'🏠',2);

-- CUST002 Sari Wijaya — Moderate, Privilege (income 45M)
INSERT INTO CUSTOMER_INCOME_SOURCES (CUSTOMER_ID,SOURCE_NAME,SOURCE_TYPE,AMOUNT,UNIT_COUNT,ICON,SORT_ORDER)
VALUES ('CUST002','Gaji (Profesional)','salary',35000000,NULL,'💼',1);
INSERT INTO CUSTOMER_INCOME_SOURCES (CUSTOMER_ID,SOURCE_NAME,SOURCE_TYPE,AMOUNT,UNIT_COUNT,ICON,SORT_ORDER)
VALUES ('CUST002','Investasi (Dividen)','dividend',10000000,NULL,'📈',2);

-- CUST003 Hendra Kusuma — Aggressive, Prioritas (income 120M)
INSERT INTO CUSTOMER_INCOME_SOURCES (CUSTOMER_ID,SOURCE_NAME,SOURCE_TYPE,AMOUNT,UNIT_COUNT,ICON,SORT_ORDER)
VALUES ('CUST003','Usaha Properti','business',90000000,NULL,'🏗',1);
INSERT INTO CUSTOMER_INCOME_SOURCES (CUSTOMER_ID,SOURCE_NAME,SOURCE_TYPE,AMOUNT,UNIT_COUNT,ICON,SORT_ORDER)
VALUES ('CUST003','Portofolio Saham','dividend',30000000,NULL,'📊',2);

-- CUST004 Dewi Lestari — Moderate, Privilege (income 55M)
INSERT INTO CUSTOMER_INCOME_SOURCES (CUSTOMER_ID,SOURCE_NAME,SOURCE_TYPE,AMOUNT,UNIT_COUNT,ICON,SORT_ORDER)
VALUES ('CUST004','Gaji (Dokter Spesialis)','salary',45000000,NULL,'🏥',1);
INSERT INTO CUSTOMER_INCOME_SOURCES (CUSTOMER_ID,SOURCE_NAME,SOURCE_TYPE,AMOUNT,UNIT_COUNT,ICON,SORT_ORDER)
VALUES ('CUST004','Praktik Pribadi','business',10000000,NULL,'🩺',2);

-- CUST005 Rudi Santoso — Conservative, Prioritas (income 65M)
INSERT INTO CUSTOMER_INCOME_SOURCES (CUSTOMER_ID,SOURCE_NAME,SOURCE_TYPE,AMOUNT,UNIT_COUNT,ICON,SORT_ORDER)
VALUES ('CUST005','Pension (Direktur BUMN)','pension',45000000,NULL,'🏛',1);
INSERT INTO CUSTOMER_INCOME_SOURCES (CUSTOMER_ID,SOURCE_NAME,SOURCE_TYPE,AMOUNT,UNIT_COUNT,ICON,SORT_ORDER)
VALUES ('CUST005','Rental Income','rental',20000000,3,'🏠',2);

-- CUST006 Reza Pratama — Aggressive, Regular (income 18M)
INSERT INTO CUSTOMER_INCOME_SOURCES (CUSTOMER_ID,SOURCE_NAME,SOURCE_TYPE,AMOUNT,UNIT_COUNT,ICON,SORT_ORDER)
VALUES ('CUST006','Gaji (Tech Startup)','salary',12000000,NULL,'💻',1);
INSERT INTO CUSTOMER_INCOME_SOURCES (CUSTOMER_ID,SOURCE_NAME,SOURCE_TYPE,AMOUNT,UNIT_COUNT,ICON,SORT_ORDER)
VALUES ('CUST006','Freelance Konsultan','freelance',6000000,NULL,'🔧',2);

-- CUST007 Mega Wulandari — Moderate, Privilege (income 72M)
INSERT INTO CUSTOMER_INCOME_SOURCES (CUSTOMER_ID,SOURCE_NAME,SOURCE_TYPE,AMOUNT,UNIT_COUNT,ICON,SORT_ORDER)
VALUES ('CUST007','Gaji (CFO)','salary',60000000,NULL,'💼',1);
INSERT INTO CUSTOMER_INCOME_SOURCES (CUSTOMER_ID,SOURCE_NAME,SOURCE_TYPE,AMOUNT,UNIT_COUNT,ICON,SORT_ORDER)
VALUES ('CUST007','Investasi (ORI/Reksa Dana)','dividend',12000000,NULL,'📈',2);

COMMIT;
BEGIN DBMS_OUTPUT.PUT_LINE('[2] Income sources data inserted (7 customers x 2 sources).'); END;
/

-- =============================================================================
-- STEP 3: CREDIT_CARDS table
-- =============================================================================

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CREDIT_CARDS PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE CREDIT_CARDS (
  CARD_ID            NUMBER         GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CUSTOMER_ID        VARCHAR2(20)   NOT NULL REFERENCES CUSTOMERS(CUSTOMER_ID),
  CARD_NUMBER_MASKED VARCHAR2(20)   NOT NULL,  -- e.g. "**** **** **** 4521"
  CARD_TYPE          VARCHAR2(30)   DEFAULT 'Visa',  -- Visa / Mastercard / JCB
  CARD_BRAND         VARCHAR2(30)   DEFAULT 'Danamon Visa',
  CREDIT_LIMIT       NUMBER(20,2)   NOT NULL,
  OUTSTANDING        NUMBER(20,2)   DEFAULT 0,
  MIN_PAYMENT        NUMBER(20,2)   DEFAULT 0,
  PAYMENT_STATUS     VARCHAR2(20)   DEFAULT 'Current',  -- Current / Missed / Late
  LAST_PAYMENT_DATE  DATE           DEFAULT NULL,
  MISSED_MONTH       VARCHAR2(20)   DEFAULT NULL,  -- e.g. "Apr 2026"
  DUE_DATE           NUMBER(2)      DEFAULT 25,   -- day of month
  IS_ACTIVE          NUMBER(1)      DEFAULT 1,
  ISSUED_DATE        DATE           DEFAULT SYSDATE,
  CREATED_AT         TIMESTAMP      DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_CC_CUST ON CREDIT_CARDS(CUSTOMER_ID);

BEGIN DBMS_OUTPUT.PUT_LINE('[3] CREDIT_CARDS created.'); END;
/

-- CUST001 Budi Santoso — Missed Apr 2026 (matches screenshot)
INSERT INTO CREDIT_CARDS (CUSTOMER_ID,CARD_NUMBER_MASKED,CARD_TYPE,CARD_BRAND,CREDIT_LIMIT,OUTSTANDING,MIN_PAYMENT,PAYMENT_STATUS,LAST_PAYMENT_DATE,MISSED_MONTH,DUE_DATE,ISSUED_DATE)
VALUES ('CUST001','**** **** **** 4521','Visa','Danamon Visa Prioritas',50000000,2500000,250000,'Missed',DATE '2026-03-25','Apr 2026',25,DATE '2020-01-15');

-- CUST002 Sari Wijaya — Current
INSERT INTO CREDIT_CARDS (CUSTOMER_ID,CARD_NUMBER_MASKED,CARD_TYPE,CARD_BRAND,CREDIT_LIMIT,OUTSTANDING,MIN_PAYMENT,PAYMENT_STATUS,LAST_PAYMENT_DATE,MISSED_MONTH,DUE_DATE,ISSUED_DATE)
VALUES ('CUST002','**** **** **** 7832','Visa','Danamon Visa Privilege',30000000,4750000,475000,'Current',DATE '2026-05-25',NULL,25,DATE '2019-06-10');

-- CUST003 Hendra Kusuma — Current, high limit
INSERT INTO CREDIT_CARDS (CUSTOMER_ID,CARD_NUMBER_MASKED,CARD_TYPE,CARD_BRAND,CREDIT_LIMIT,OUTSTANDING,MIN_PAYMENT,PAYMENT_STATUS,LAST_PAYMENT_DATE,MISSED_MONTH,DUE_DATE,ISSUED_DATE)
VALUES ('CUST003','**** **** **** 1290','Mastercard','Danamon Mastercard Black',100000000,12500000,1250000,'Current',DATE '2026-05-20',NULL,20,DATE '2018-03-01');

-- CUST004 Dewi Lestari — Late (but paid)
INSERT INTO CREDIT_CARDS (CUSTOMER_ID,CARD_NUMBER_MASKED,CARD_TYPE,CARD_BRAND,CREDIT_LIMIT,OUTSTANDING,MIN_PAYMENT,PAYMENT_STATUS,LAST_PAYMENT_DATE,MISSED_MONTH,DUE_DATE,ISSUED_DATE)
VALUES ('CUST004','**** **** **** 6673','Visa','Danamon Visa Privilege',25000000,8900000,890000,'Current',DATE '2026-05-28',NULL,25,DATE '2021-09-15');

-- CUST005 Rudi Santoso — Current, conservative usage
INSERT INTO CREDIT_CARDS (CUSTOMER_ID,CARD_NUMBER_MASKED,CARD_TYPE,CARD_BRAND,CREDIT_LIMIT,OUTSTANDING,MIN_PAYMENT,PAYMENT_STATUS,LAST_PAYMENT_DATE,MISSED_MONTH,DUE_DATE,ISSUED_DATE)
VALUES ('CUST005','**** **** **** 3344','Visa','Danamon Visa Prioritas',75000000,1200000,120000,'Current',DATE '2026-05-25',NULL,25,DATE '2015-05-01');

-- CUST006 Reza Pratama — Late 1 month
INSERT INTO CREDIT_CARDS (CUSTOMER_ID,CARD_NUMBER_MASKED,CARD_TYPE,CARD_BRAND,CREDIT_LIMIT,OUTSTANDING,MIN_PAYMENT,PAYMENT_STATUS,LAST_PAYMENT_DATE,MISSED_MONTH,DUE_DATE,ISSUED_DATE)
VALUES ('CUST006','**** **** **** 9901','Mastercard','Danamon Mastercard',10000000,3200000,320000,'Missed',DATE '2026-04-25','May 2026',25,DATE '2023-02-20');

-- CUST007 Mega Wulandari — Current
INSERT INTO CREDIT_CARDS (CUSTOMER_ID,CARD_NUMBER_MASKED,CARD_TYPE,CARD_BRAND,CREDIT_LIMIT,OUTSTANDING,MIN_PAYMENT,PAYMENT_STATUS,LAST_PAYMENT_DATE,MISSED_MONTH,DUE_DATE,ISSUED_DATE)
VALUES ('CUST007','**** **** **** 5518','Visa','Danamon Visa Privilege',40000000,9800000,980000,'Current',DATE '2026-05-25',NULL,25,DATE '2017-11-30');

COMMIT;
BEGIN DBMS_OUTPUT.PUT_LINE('[3] Credit card data inserted (7 customers).'); END;
/

-- =============================================================================
-- VERIFICATION
-- =============================================================================

SELECT c.CUSTOMER_ID, c.FULL_NAME, c.CIF_NUMBER,
       SUM(i.AMOUNT) AS TOTAL_INCOME_FROM_SOURCES,
       c.MONTHLY_INCOME AS DB_MONTHLY_INCOME
FROM   CUSTOMERS c
LEFT JOIN CUSTOMER_INCOME_SOURCES i ON i.CUSTOMER_ID = c.CUSTOMER_ID
GROUP BY c.CUSTOMER_ID, c.FULL_NAME, c.CIF_NUMBER, c.MONTHLY_INCOME
ORDER BY c.CUSTOMER_ID;

SELECT CUSTOMER_ID, CARD_NUMBER_MASKED, OUTSTANDING, PAYMENT_STATUS, MISSED_MONTH
FROM   CREDIT_CARDS
ORDER BY CUSTOMER_ID;

BEGIN
  DBMS_OUTPUT.PUT_LINE('==========================================');
  DBMS_OUTPUT.PUT_LINE('Migration 15 complete.');
  DBMS_OUTPUT.PUT_LINE('New tables: CUSTOMER_INCOME_SOURCES, CREDIT_CARDS');
  DBMS_OUTPUT.PUT_LINE('New column: CUSTOMERS.CIF_NUMBER');
  DBMS_OUTPUT.PUT_LINE('==========================================');
END;
/
