CREATE USER PAF IDENTIFIED BY Danamon2045Kita DEFAULT TABLESPACE USERS QUOTA unlimited ON USERS;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, CREATE TYPE, CREATE PROCEDURE, CREATE VIEW, CREATE SYNONYM TO PAF;
GRANT READ, WRITE ON DIRECTORY DATA_PUMP_DIR TO PAF;
GRANT SELECT ON V$PARAMETER TO PAF;
GRANT SELECT ON V_$PARAMETER TO PAF;

GRANT DWROLE TO PAF;


CREATE USER AAI_RO_PAF IDENTIFIED BY Danamon2045Kita ACCOUNT UNLOCK;

DROP USER AAI_RO_PAF;

GRANT CREATE SESSION TO AAI_RO_PAF;
exit;

--Tambahkan grant ini untuk resolve problem ini
--Creating read only DB user
--✗ Read only DB user creation failed: Read-only user creation failed: ORA-01031: insufficient privileges
--Cannot proceed with installation due to read only DB user creation failure.

GRANT CREATE USER TO PAF WITH ADMIN OPTION;
GRANT ALTER USER TO PAF WITH ADMIN OPTION;
GRANT DROP USER TO PAF WITH ADMIN OPTION;
GRANT CREATE SESSION TO PAF WITH ADMIN OPTION;
GRANT GRANT ANY ROLE TO PAF WITH ADMIN OPTION;