-- ═══════════════════════════════════════════════════════════════════
-- Intelligence RM Platform — Oracle Autonomous Database 26ai Schema
-- ═══════════════════════════════════════════════════════════════════

-- ───────────────────────────────────────────────────────────────────
-- 1. RM USERS
-- ───────────────────────────────────────────────────────────────────
CREATE TABLE RM_USERS (
  USER_ID       VARCHAR2(50)  PRIMARY KEY,
  USERNAME      VARCHAR2(100) NOT NULL UNIQUE,
  PASSWORD_HASH VARCHAR2(255) NOT NULL,
  FULL_NAME     VARCHAR2(200) NOT NULL,
  ROLE          VARCHAR2(100) DEFAULT 'Relationship Manager',
  INITIALS      VARCHAR2(10),
  EMAIL         VARCHAR2(200),
  BRANCH        VARCHAR2(100),
  IS_ACTIVE     NUMBER(1)     DEFAULT 1,
  LAST_LOGIN    TIMESTAMP,
  CREATED_AT    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

-- ───────────────────────────────────────────────────────────────────
-- 2. CUSTOMERS
-- ───────────────────────────────────────────────────────────────────
CREATE TABLE CUSTOMERS (
  CUSTOMER_ID   VARCHAR2(50)   PRIMARY KEY,
  FULL_NAME     VARCHAR2(200)  NOT NULL,
  INITIALS      VARCHAR2(10),
  AVATAR_COLOR  VARCHAR2(200),
  AGE           NUMBER(3),
  GENDER        VARCHAR2(20),
  EMAIL         VARCHAR2(200),
  PHONE         VARCHAR2(30),
  ADDRESS       CLOB,
  RISK_PROFILE  VARCHAR2(50),  -- Conservative / Moderate / Aggressive
  TIER          VARCHAR2(50),  -- prioritas / privilege / regular
  TIER_LABEL    VARCHAR2(100),
  MONTHLY_INCOME NUMBER(20,2),
  TOTAL_AUM      NUMBER(20,2),
  RM_USER_ID    VARCHAR2(50)   REFERENCES RM_USERS(USER_ID),
  KYC_STATUS    VARCHAR2(30)   DEFAULT 'Verified',
  KYC_EXPIRY    DATE,
  NOTES         CLOB,
  CREATED_AT    TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT    TIMESTAMP      DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_CUSTOMERS_RM   ON CUSTOMERS(RM_USER_ID);
CREATE INDEX IDX_CUSTOMERS_TIER ON CUSTOMERS(TIER);

-- ───────────────────────────────────────────────────────────────────
-- 3. PRODUCT CATALOG (bank products available for recommendation)
-- ───────────────────────────────────────────────────────────────────
CREATE TABLE PRODUCT_CATALOG (
  PRODUCT_ID    VARCHAR2(50)   PRIMARY KEY,
  PRODUCT_NAME  VARCHAR2(200)  NOT NULL,
  CATEGORY      VARCHAR2(100), -- deposito / reksa_dana / obligasi / asuransi / tabungan
  DESCRIPTION   CLOB,
  INTEREST_RATE NUMBER(6,4),   -- annual rate
  MIN_AMOUNT    NUMBER(20,2),
  MAX_AMOUNT    NUMBER(20,2),
  TENURE_MONTHS NUMBER(5),
  RISK_LEVEL    VARCHAR2(30),  -- low / medium / high
  IS_ACTIVE     NUMBER(1)      DEFAULT 1,
  VALID_FROM    DATE,
  VALID_TO      DATE,
  FEATURES      CLOB,          -- JSON array of feature strings
  CREATED_AT    TIMESTAMP      DEFAULT CURRENT_TIMESTAMP
);

-- ───────────────────────────────────────────────────────────────────
-- 4. CUSTOMER PRODUCTS (holdings)
-- ───────────────────────────────────────────────────────────────────
CREATE TABLE CUSTOMER_PRODUCTS (
  HOLDING_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CUSTOMER_ID   VARCHAR2(50)  NOT NULL REFERENCES CUSTOMERS(CUSTOMER_ID),
  PRODUCT_ID    VARCHAR2(50)  REFERENCES PRODUCT_CATALOG(PRODUCT_ID),
  PRODUCT_NAME  VARCHAR2(200),
  CATEGORY      VARCHAR2(100),
  AMOUNT        NUMBER(20,2)  NOT NULL,
  INTEREST_RATE NUMBER(6,4),
  START_DATE    DATE,
  MATURITY_DATE DATE,
  STATUS        VARCHAR2(30)  DEFAULT 'Active',  -- Active / Matured / Redeemed
  RETURN_PCT    NUMBER(8,4),  -- current return percentage
  CREATED_AT    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_HOLDINGS_CUSTOMER ON CUSTOMER_PRODUCTS(CUSTOMER_ID);
CREATE INDEX IDX_HOLDINGS_MATURITY  ON CUSTOMER_PRODUCTS(MATURITY_DATE, STATUS);

-- ───────────────────────────────────────────────────────────────────
-- 5. ALERTS
-- ───────────────────────────────────────────────────────────────────
CREATE TABLE ALERTS (
  ALERT_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CUSTOMER_ID   VARCHAR2(50)  REFERENCES CUSTOMERS(CUSTOMER_ID),
  ALERT_TYPE    VARCHAR2(100), -- maturity / portfolio_loss / kyc_expiry / cc_missed / campaign
  SEVERITY      VARCHAR2(20),  -- high / medium / low
  TITLE         VARCHAR2(500),
  MESSAGE       CLOB,
  METRIC_KEY    VARCHAR2(200),
  METRIC_VALUE  VARCHAR2(200),
  THRESHOLD     VARCHAR2(200),
  STATUS        VARCHAR2(30)   DEFAULT 'Open',  -- Open / Acknowledged / Resolved
  TRIGGERED_AT  TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
  RESOLVED_AT   TIMESTAMP,
  RESOLVED_BY   VARCHAR2(50)   REFERENCES RM_USERS(USER_ID)
);

CREATE INDEX IDX_ALERTS_CUSTOMER ON ALERTS(CUSTOMER_ID);
CREATE INDEX IDX_ALERTS_STATUS   ON ALERTS(STATUS, SEVERITY);

-- ───────────────────────────────────────────────────────────────────
-- 6. CAMPAIGNS
-- ───────────────────────────────────────────────────────────────────
CREATE TABLE CAMPAIGNS (
  CAMPAIGN_ID   VARCHAR2(50)   PRIMARY KEY,
  NAME          VARCHAR2(200)  NOT NULL,
  DESCRIPTION   CLOB,
  TYPE          VARCHAR2(100), -- privilege_upgrade / product_placement / retention
  STATUS        VARCHAR2(30)   DEFAULT 'Active',
  START_DATE    DATE,
  END_DATE      DATE,
  RULES         CLOB,          -- JSON rules array
  CREATED_AT    TIMESTAMP      DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CAMPAIGN_ELIGIBILITY (
  ELIGIBILITY_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CAMPAIGN_ID    VARCHAR2(50)  NOT NULL REFERENCES CAMPAIGNS(CAMPAIGN_ID),
  CUSTOMER_ID    VARCHAR2(50)  NOT NULL REFERENCES CUSTOMERS(CUSTOMER_ID),
  IS_ELIGIBLE    NUMBER(1)     DEFAULT 0,
  RULE1_PASS     NUMBER(1)     DEFAULT 0,
  RULE2_PASS     NUMBER(1)     DEFAULT 0,
  RULE3_PASS     NUMBER(1)     DEFAULT 0,
  AUM_3M_AVG     NUMBER(20,2),
  NOTES          CLOB,
  SCANNED_AT     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT UQ_CAMP_CUST UNIQUE (CAMPAIGN_ID, CUSTOMER_ID)
);

-- ───────────────────────────────────────────────────────────────────
-- 7. MEETING NOTES
-- ───────────────────────────────────────────────────────────────────
CREATE TABLE MEETING_NOTES (
  NOTE_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CUSTOMER_ID   VARCHAR2(50)  NOT NULL REFERENCES CUSTOMERS(CUSTOMER_ID),
  RM_USER_ID    VARCHAR2(50)  REFERENCES RM_USERS(USER_ID),
  MEETING_DATE  DATE,
  NOTE_TYPE     VARCHAR2(100), -- meeting / call / visit / inquiry
  SUMMARY       CLOB,
  TOPICS        CLOB,          -- JSON array
  PRODUCTS_DISCUSSED CLOB,     -- JSON array
  FOLLOW_UP     CLOB,
  CREATED_AT    TIMESTAMP      DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_NOTES_CUSTOMER ON MEETING_NOTES(CUSTOMER_ID);

-- ───────────────────────────────────────────────────────────────────
-- 8. AUDIT LOG
-- ───────────────────────────────────────────────────────────────────
CREATE TABLE AUDIT_LOG (
  LOG_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USER_ID       VARCHAR2(50)  REFERENCES RM_USERS(USER_ID),
  ACTION        VARCHAR2(200) NOT NULL,
  ENTITY_TYPE   VARCHAR2(100),
  ENTITY_ID     VARCHAR2(100),
  DETAILS       CLOB,         -- JSON
  IP_ADDRESS    VARCHAR2(50),
  CREATED_AT    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_AUDIT_USER ON AUDIT_LOG(USER_ID, CREATED_AT DESC);

-- ───────────────────────────────────────────────────────────────────
-- 9. AI ANALYSIS CACHE (store past LLM results to avoid re-calling)
-- ───────────────────────────────────────────────────────────────────
CREATE TABLE AI_ANALYSIS_CACHE (
  CACHE_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CACHE_KEY     VARCHAR2(500) NOT NULL UNIQUE,
  SCENARIO      VARCHAR2(50), -- maturity / recommendation / campaign / alert / copilot
  CUSTOMER_ID   VARCHAR2(50),
  PROMPT_HASH   VARCHAR2(64),
  RESULT        CLOB NOT NULL, -- JSON result
  MODEL_USED    VARCHAR2(200),
  TOKENS_USED   NUMBER,
  CREATED_AT    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  EXPIRES_AT    TIMESTAMP
);

-- ═══════════════════════════════════════════════════════════════════
-- VECTOR TABLES (Oracle 26ai / 23ai VECTOR type)
-- ═══════════════════════════════════════════════════════════════════

-- 10. Customer profile embeddings (for RAG similarity search)
CREATE TABLE CUSTOMER_EMBEDDINGS (
  EMBED_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CUSTOMER_ID   VARCHAR2(50)  NOT NULL REFERENCES CUSTOMERS(CUSTOMER_ID),
  CONTENT_TYPE  VARCHAR2(50)  NOT NULL, -- profile / notes / products / goals
  CONTENT       CLOB          NOT NULL,
  EMBEDDING     VECTOR(1024, FLOAT32)   NOT NULL,
  MODEL_USED    VARCHAR2(200),
  CREATED_AT    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

CREATE VECTOR INDEX IDX_CUST_EMBED_VEC ON CUSTOMER_EMBEDDINGS(EMBEDDING)
  ORGANIZATION NEIGHBOR PARTITIONS
  WITH DISTANCE COSINE
  WITH TARGET ACCURACY 95;

-- 11. Meeting notes embeddings
CREATE TABLE MEETING_NOTES_EMBEDDINGS (
  EMBED_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOTE_ID       NUMBER        NOT NULL REFERENCES MEETING_NOTES(NOTE_ID),
  CUSTOMER_ID   VARCHAR2(50)  NOT NULL REFERENCES CUSTOMERS(CUSTOMER_ID),
  CONTENT       CLOB          NOT NULL,
  EMBEDDING     VECTOR(1024, FLOAT32) NOT NULL,
  MODEL_USED    VARCHAR2(200),
  CREATED_AT    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

CREATE VECTOR INDEX IDX_NOTES_EMBED_VEC ON MEETING_NOTES_EMBEDDINGS(EMBEDDING)
  ORGANIZATION NEIGHBOR PARTITIONS
  WITH DISTANCE COSINE
  WITH TARGET ACCURACY 95;

-- 12. Product catalog embeddings
CREATE TABLE PRODUCT_EMBEDDINGS (
  EMBED_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PRODUCT_ID    VARCHAR2(50)  NOT NULL REFERENCES PRODUCT_CATALOG(PRODUCT_ID),
  CONTENT       CLOB          NOT NULL,
  EMBEDDING     VECTOR(1024, FLOAT32) NOT NULL,
  MODEL_USED    VARCHAR2(200),
  CREATED_AT    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

CREATE VECTOR INDEX IDX_PROD_EMBED_VEC ON PRODUCT_EMBEDDINGS(EMBEDDING)
  ORGANIZATION NEIGHBOR PARTITIONS
  WITH DISTANCE COSINE
  WITH TARGET ACCURACY 95;

-- 13. Market context embeddings (historical market events for Scenario 3 RAG)
CREATE TABLE MARKET_CONTEXT_EMBEDDINGS (
  EMBED_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EVENT_DATE    DATE,
  TITLE         VARCHAR2(500),
  CONTENT       CLOB          NOT NULL,
  EMBEDDING     VECTOR(1024, FLOAT32) NOT NULL,
  MODEL_USED    VARCHAR2(200),
  CREATED_AT    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

CREATE VECTOR INDEX IDX_MKT_EMBED_VEC ON MARKET_CONTEXT_EMBEDDINGS(EMBEDDING)
  ORGANIZATION NEIGHBOR PARTITIONS
  WITH DISTANCE COSINE
  WITH TARGET ACCURACY 95;
